# Generated by Django 5.0.4 on 2024-04-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('application_start', models.DateTimeField()),
                ('application_end', models.DateTimeField()),
            ],
        ),
    ]
